### ISSUE TITLE
Disable pattern-matching on erased argument

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#142] opened 2023-02-21 16:43 UTC
Currently, you are allowed to pattern-match on erased arguments if there is only one constructor available. Consider:

```agda
coerce : @0 a ≡ b → a → b
coerce refl x = x
{-# COMPILE AGDA2HS coerce #-}
```

We get the following Haskell code, that does not type-check:

```agda
coerce :: a -> b
coerce x = x
```

For propositional equality specifically, we may want to compile to equality constraints (#140) when the equality argument is an instance, or to Haskell's builtin propositional equality GADT when the equality is *not* erased.
In general though, probably best to disable pattern-matching on erased arguments entirely, especially if our goal is to produce valid Haskell code.

**Comment by jespercockx** [comment] 2023-02-22 08:42
Note that in the current development branch of Agda, one needs to enable the `--erased-matches` option to match on single-constructor erased arguments: https://agda.readthedocs.io/en/latest/tools/command-line-options.html#cmdoption-erased-matches

**Comment by flupe** [comment] 2023-02-22 09:20
Right. Because this is only a concern for *compiled* definitions, I don't think we can just disallow the (soon to be) language option with agda2hs. Don't know how easy it is to figure out if a pattern in a clause corresponds to an erased argument.

**Comment by jespercockx** [comment] 2023-02-22 09:43
The flag should still allow matching on erased arguments *in erased definitions*, so for non-compiled definitions you could just mark them as erased.

**Comment by jespercockx** [comment] 2023-03-01 09:56
Hm, I'm a bit torn on whether this should be fixed for agda2hs 1.0. It would be a lot easier if we can just wait until the next version of Agda so we can piggyback on the new `--erased-matches` flag. @flupe do you have any example where this could lead to *valid but wrong* Haskell code being generated, or is the problem only invalid code?

**Comment by flupe** [comment] 2023-03-01 10:08
Yeah, I agree it would make things easier.

> do you have any example where this could lead to valid but wrong Haskell code being generated, or is the problem only invalid code?

Hm, it's always the issue isn't it? But it's reasonable to assume that only invalid Haskell can be outputted. Pattern-matching on a constructor may trigger unification of indices that equates more things in Agda than in Haskell, so...

This is only an issue when the (inductive family) argument is erased because otherwise you'd have to compile it to Haskell and we don't support indices yet.

**Comment by flupe** [comment] 2023-03-01 14:15
Ok @jespercockx and I found a valid reasonable use for pattern-matching on erased datatypes even in compiled definitionns: _accessibility predicates_. So maybe we shouldn't rely on the future Agda extension and detect ourselves whether the erased datatype being pattern-matched on has indices or not.

**Comment by jespercockx** [comment] 2023-04-04 16:40
I am working on a fix for this issue at https://github.com/agda/agda2hs/commit/41d63b91fcdb013b0219ff27aeee39fd09e588f4, but this breaks the test case for `HeightMirror.agda`. The problem is the first function in this file:
```agda
subst : (@0 p : @0 a → Set) {@0 m n : a} → @0 m ≡ n → p m → p n
subst p refl t = t

{-# COMPILE AGDA2HS subst transparent #-}
```
Intuitively this should be fine because the match on `refl` only forces the values of `m` and `n` to be equal, but these are erased so the resulting code is well-typed anyway. But conceptually this is quite close to the "evil" cast in the OP. I'll have to think a bit more about a more fine-grained check that still allows this use case.

**Comment by jespercockx** [comment] 2023-04-06 10:06
I found a better fix which works not by prohibiting pattern matching altogether, but instead only prohibiting forced (dot) patterns in non-erased positions. See #168.

**Closed** 2023-04-06 15:48 UTC
Labels: bug

**Comment by anuyts** [comment] 2026-03-05 16:02
While this is a good fix for now, it becomes too strict when GADTs or equality constraints become supported.
I think the correct fix should be to disallow non-erased forced patterns that are forced by erased patterns.

I don't know enough about pattern matching to understand how easy/hard this correct fix would be.

@jespercockx @zeroeightysix 

Allow:
```agda
coerce : {{ _ : a ≡ b }} → a → b
coerce {{refl}} x = x
{-# COMPILE AGDA2HS coerce #-}
```
```haskell
coerce :: (a ~ b) => a -> b
coerce x = x
```

Disallow:
```agda
coerce : @0 a ≡ b → a → b
coerce refl x = x
{-# COMPILE AGDA2HS coerce #-}
```
```haskell
coerce :: a -> b
coerce x = x
```

Allow (although the Haskell function will be difficult to call, but I'd say that's the programmers responsibility):
```agda
coerce : {{ _ : a ≡ b }} → (@0 b → c) → @0 a → c
coerce {{refl}} f = f
{-# COMPILE AGDA2HS coerce #-}
```
```haskell
coerce :: (a ~ b) => c -> c
coerce x = x
```

Allow:
```agda
coerce : @0 a ≡ b → (@0 b → c) → @0 a → c
coerce refl f = f
{-# COMPILE AGDA2HS coerce #-}
```
```haskell
coerce :: c -> c
coerce x = x
```

**Comment by jespercockx** [comment] 2026-03-05 16:33
I agree that this fix no longer works when we want to support GADTs, and with the test cases you give. Unfortunately I'm not sure if it is easy or even possible to determine which pattern match a forced pattern was forced by. Even if we could in theory change Agda's index unification algorithm to keep track of this information, this is not something that a backend such as agda2hs can instrument.

So there's basically two options:

1. Add a new flag to Agda itself that enforced that non-erased arguments can only be forced by matching on a non-erased argument with non-erased indices. Then wait until this option is released so we can base agda2hs on that version of Agda, so not very attractive. 
2. Figure out some way to approximate this with a separate check implemented in agda2hs itself. I'm not sure what would be the best way to do this just yet, but I'll think about it.

**Comment by jespercockx** [comment] 2026-03-05 16:36
Oh I just thought of something that might work. You could look at the original type of every pattern in the clause, and if it is either in a erased position itself or its index is erased, require that all of the variables in its type are also bound in erased positions. This is a bit of an over-approximation (since a variable could appear in the type but not get solved by the pattern match) but perhaps it's good enough for a first version.

We already have the type of each pattern when we compile it, so we could even just do this check right at the point where we compile the patterns. Currently we do not traverse the erased parts of a pattern during compilation so that would have to change, but I don't see a fundamental issue with it.

**Comment by anuyts** [comment] 2026-03-05 16:41
> ... and if it is either in a erased position itself or its index is erased, require that all of the variables in its type are also bound in erased positions.

Do you mean: ... and:
- if it is in an erased position itself, require that all of the variables in its type are also bound in erased positions,
- if its index is erased, require that all variables in that index are also bound in erased positions.

**Comment by anuyts** [comment] 2026-03-05 16:43
> 1. Add a new flag to Agda itself that enforced that non-erased arguments can only be forced by matching on a non-erased argument with non-erased indices. Then wait until this option is released so we can base agda2hs on that version of Agda, so not very attractive.

While I would advocate for such behaviour for most modalities, I wonder if it is in line with the intended semantics of `@0` in Agda?

**Comment by jespercockx** [comment] 2026-03-05 17:14
> > ... and if it is either in a erased position itself or its index is erased, require that all of the variables in its type are also bound in erased positions.
> 
> Do you mean: ... and:
> 
>     * if it is in an erased position itself, require that all of the variables in its type are also bound in erased positions,
> 
>     * if its index is erased, require that all variables in that index are also bound in erased positions.

Yes, that's what I meant.

> While I would advocate for such behaviour for most modalities, I wonder if it is in line with the intended semantics of @0 in Agda?

I'm not sure if such behavior would make sense as the default. My intuitions about erasure have been off (or at least misaligned with other users of erasure) in the past. But recently @nad also asked some interesting questions about the interaction between erasure and dependent pattern matching in https://github.com/agda/agda/issues/8420, I'll have to think if the proposed changes there correspond in any way to what we're discussing here.

**Comment by anuyts** [comment] 2026-03-09 10:38
FWIW, this paper seems to provide theoretical foundations for pattern matching on erased equality proofs.
@nad Nils Anders Danielsson, Erased Postulates, Erased Matches and Identity Types
https://www.cse.chalmers.se/~nad/publications/danielsson-box-cong.pdf

**Comment by nad** [comment] 2026-03-12 12:47
> FWIW, this paper seems to provide theoretical foundations for pattern matching on erased equality proofs.

The soundness theorem is stated in terms of translation to an untyped language, and the translation basically removes all primitives related to the identity type. You translate to Haskell, and the goal is to produce well-typed, idiomatic Haskell code, right? If the Haskell code computes like the code produced by the translation to the untyped language, then one could perhaps make use of the soundness theorem in some way, assuming that the Haskell code is well-typed.
