### ISSUE TITLE
Allow higher-kinded records/datatypes

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#143] opened 2023-02-22 13:27 UTC
Just tried defining my own record (compiled to a Haskell datatype) parametrized by some monad, and was dumbfounded that it is somehow rejected, as parameters are apparently only allowed to have kind `*` (i.e `Set`).

```agda
record Kleisli (m : Set → Set) (a b : Set) : Set where
  constructor MkKleisli ; field runKleisli : a → m b
{-# COMPILE AGDA2HS Kleisli #-}
```

This throws the following error: `Kind not supported: Set → Set`, from [there](https://github.com/agda/agda2hs/blob/master/src/Agda2Hs/Compile/Type.hs#L199).

**Comment by jespercockx** [comment] 2023-02-22 14:40
Duplicate of #38?

**Closed** 2023-02-22 14:41 UTC
Labels: duplicate
