### ISSUE TITLE
Bug: Miscompilation of operator precedence

### ISSUE THREAD

**Issue by JonathanBrouwer** [agda/agda2hs#54] opened 2021-04-21 21:43 UTC
When compiling this code: 
```agda
module Testing where

open import Haskell.Prelude

infix 8 _^_ -- Higher priority than +, the usual precedence
_^_ : Nat -> Nat -> Nat
_^_ b zero = 1
_^_ b (suc e) = b * (b ^ e) 
{-# COMPILE AGDA2HS _^_ #-}

x = 2 ^ (2 + 3)
{-# COMPILE AGDA2HS x #-}
```
The following haskell is generated
```haskell
module Testing where

import Numeric.Natural (Natural)

(^) :: Natural -> Natural -> Natural
b ^ zero = 1
b ^ suc e = b * b ^ e

x :: Natural
x = 2 ^ 2 + 3
```

Note that there is nothing funky going on with the precedence, it's exactly as would be expected, yet it generates wrong code.
In fact, I can never get agda2hs to generate parentheses in infix sequences, no matter the parentheses used in the agda code

**Comment by JonathanBrouwer** [comment] 2021-04-22 12:33
You don't even need a custom operator definition, even `10 - (2 + 3)` does not compile correctly

**Comment by omelkonian** [comment] 2021-04-24 12:29
Yep, this is a feature we do not currently support -- see the un-checked item in the [README](https://github.com/agda/agda2hs#future-work).

Closing as this is a duplicate of #41.

**Comment by jespercockx** [comment] 2021-04-25 17:21
Even without using explicit operator precedences, shouldn't at least an expression such as `10 - (2 + 3)` (with all parenthesis included) be compiled to an equivalent expression in Haskell?

**Comment by UlfNorell** [comment] 2021-04-26 06:21
Yes, handling the default fixities is a slightly different issue than handling user-given ones.

**Closed** 2021-05-03 07:29 UTC
